### ISSUE TITLE
Multiple graphql mutations start the a transaction

### ISSUE THREAD

**Issue by mywin** [graphile/crystal#1351]
### Feature description

Why not add multiple Multiple mutations to the same transaction in source code

Below is a demo of one of my test in postgraphile\build\postgraphile\http\createPostGraphileHttpRequestHandler.js，i test is ok

### Motivating example
  
    
    // start the a transaction   
    await graphqlContext.pgClient.query('SAVEPOINT custom_xxx_start')
    const graphqlResult = await graphql_1.execute(gqlSchema, queryDocumentAst, null, graphqlContext, variables, operationName);
    if (graphqlResult && graphqlResult.errors) {
        // rollback to the a transaction  
       await graphqlContext.pgClient.query('ROLLBACK TO custom_xxx_start')
    }
    // release to the a transaction  
    await graphqlContext.pgClient.query('RELEASE SAVEPOINT custom_xxx_start')

    // PostGraphiQL test
    mutation MyMutation {
      createClass(input: {class: {name: "1-1"}}) {
        clientMutationId
      }
      createStudent(input: {student: {name: "zhangsan"}}) {
        clientMutationId
      }
    }

### Supporting development

I [tick all that apply]:

- [x] am interested in building this feature myself
- [ ] am interested in collaborating on building this feature
- [ ] am willing to help testing this feature before it's released
- [ ] am willing to write a test-driven test suite for this feature (before it exists)
- [ ] am a [Graphile sponsor](https://www.graphile.org/sponsor/) ❤️
- [ ] have an active [support or consultancy contract](https://www.graphile.org/support/) with Graphile

**Comment by benjie** [comment]
This is something we'll likely support as part of the V5 changes.

**Comment by benjie** [comment]
Re-reading this issue I don't really understand it - all of the mutations are already in the same transaction (with savepoints around each one) in V4 already. V5's transaction management has evolved; you can provide your own PostgreSQL adaptor via the GraphQL context which gives you stronger control over what you want from transactions; so I'm going to close this as "probably solved".
