### ISSUE TITLE
Functions of compound types not sortable (despite smart tag)

### ISSUE THREAD

**Issue by jsimonlane** [graphile/crystal#1450]
### Summary
[The docs](https://www.graphile.org/postgraphile/smart-tags/#sortable) state that:
> Functions returning `SETOF` a composite type (e.g. a table type, record type, or another type with "column"-like attributes): adds the `orderBy` argument to this connection, allowing to sort the set by its columns/attributes.

HOWEVER: an `orderBy` field does not appear when I created my own composite data type using `CREATE TYPE`.

[This commit](https://github.com/graphile/graphile-engine/pull/378/commits/452ecf42d09f04e6a58f244af5c1263d9805f10f) put the sortablility in place -- however, it only ever tested record types from tables, and not custom created ones. This is likely why the bug got through.

### Steps to reproduce

Create the following test database:
```sql
-- All this occurs in a database called 'test_db' -- run `createdb test_db`

drop schema if exists test cascade;
create schema test;

-- Create a basic table which we'll use to get some values.
drop table if exists test.basic_data;
create table test.basic_data(
    a int primary key,
    b int,
    c text
);

-- populate the table with a bit of dummy data
insert into test.basic_data(a, b, c) values
(1, 2, 'hi'),
(3, 4, 'there'),
(5, 6, 'friend');

-- A compound type we'll later try to query
drop type if exists test.compound_type;
create type test.compound_type as (
    x int,
    y text
);
comment on type test.compound_type is E'@sortable'; -- Hail Mary comment, hoping it would work.

------------------------------------------


-- This IS SORTABLE: A basic table select function works
drop function if exists test.f;
create function test.f() returns setof test.basic_data as $$ select * from test.basic_data $$ language sql stable;
comment on function test.f is E'@sortable';

-- However, this function is NOT sortable: a function returning a compound selection is NOT sortable (no orderBy field)
drop function if exists test.g;
create function test.g() returns setof test.compound_type as $$ 
    select a as x, c as y from test.basic_data 
$ language sql stable;
comment on function test.g is E'@sortable';
```

A little script to start the server:
```sh
npx postgraphile \
    -c postgres://localhost/test_db \
    --schema "test" \
    --enhance-graphiql \
    --allow-explain \
    --watch
```

Below is a screenshot from the PostGraphIQL query explorer. Note that function `f` CAN be sorted, but `g` CANNOT be.

<img width="321" alt="schema" src="https://user-images.githubusercontent.com/35848824/110538369-fb81e600-80f1-11eb-9904-c06d53a9b6fa.png">

### Expected results
Expected to see an 'OrderBy' field in `g`.

### Actual results

You don't see an 'OrderBy' field in `g`, but you do in `f`.

### Additional context

MacOS Catalina, 10.15.2
Node: 15.6
Postgraphile: 14.11.0
Postgres: 13.1

**Comment by benjie** [comment]
I've fixed the docs: https://github.com/graphile/graphile.github.io/commit/63aeb64ee48a743cf3667105962df94b67a407f9

Order/condition types are only generated for [selectable types](https://github.com/graphile/graphile-engine/blob/9940895db5a35f218484620d610845201278611c/packages/graphile-build-pg/src/plugins/introspectionQuery.js#L166) currently; so although the @filterable/@sortable comments enable the use of these types, since the types don't exist nothing happens.

Leaving this open as a feature request.

**Comment by benjie** [comment]
In V5, composite types can be made sortable or filterable via the [behavior system](https://postgraphile.org/postgraphile/next/behavior).
