### ISSUE TITLE
jwtSecret should not be mandatory in order to just verify JWTs

### ISSUE THREAD

**Issue by TimoStolz** [graphile/crystal#1464]
In https://github.com/graphile/postgraphile/blob/601a1086a2c10ebae4747364e199f2517d653861/src/postgraphile/http/createPostGraphileHttpRequestHandler.ts#L132, provided JWTs are ignored, if a jwtSecret is missing. However, I would expect, that JWTs would still be taken into account, if one is able to provide a jwtPublicKey – but then, just for verification, of course.

**Comment by benjie** [comment]
Yes, this does seem like it could be problematic. @speller can you lend any insight here?

Relates to https://github.com/graphile/postgraphile/pull/1089

**Comment by speller** [comment]
I agree that the secret key could be omitted for the verification-only cases.

**Comment by benjie** [comment]
Thanks for confirmation @speller :+1: 

PR welcome to address this, please ensure it comes with tests.

**Comment by benjie** [comment]
It seems this was fixed a while ago:

https://github.com/graphile/crystal/blob/ff60ed50afd082e7b425f4cf65c4ed11c4cb821f/src/postgraphile/http/createPostGraphileHttpRequestHandler.ts#L133-L134
