### ISSUE TITLE
macOS Monterey uses port 5000 for new AirPlay service by default

### ISSUE THREAD

**Issue by nodesocket** [graphile/crystal#1551]
Heads up, in the new OS **macOS Monterey** they added a new service used for AirPlay that listens on port `5000` by default. Not a huge deal to change the port for PostGraphile using `--port` but might be a good idea to change the default from `5000` as it's confusing at first when you get address already in use error. Apple obviously is not going to change from using port `5000` for their AirPlay service.

See https://developer.apple.com/forums/thread/682332 for background.

**Comment by damaon** [comment]
I suggest adding some notice about this as I was puzzled why I am getting 403 when trying to reach /graphiql

**Comment by reisr3** [comment]
This was driving me crazy. Google search does not produce any helpful results. Glad to finally have found the answer!

**Comment by benjie** [comment]
@reisr3 If you can remember (or find out) what any of your google searches were for, perhaps you could add them in a reply to this thread to help future people find it?

**Comment by damaon** [comment]
I think it would be good to detect if port is already taken and fail based on that, that would be clear. 

BTW can many apps be bound to single port? I though they can if protocol is different but last time I did this was long time ago.

**Comment by benjie** [comment]
I've added a note to the `usage-cli` docs, and to the README. Hopefully this helps.

**Comment by pmanfroi** [comment]
Great work @benjie, that was really handy!
Unless I'm missing something, you may also need to support the **port** option when using via Library instead of CLI.

**Comment by benjie** [comment]
The library doesn't bind to a port on its own, that's the responsibility of whatever webserver you're using. The examples use port 3000 :man_shrugging:

**Comment by benjie** [comment]
The default port number in V5 is 5678
