### ISSUE TITLE
@notNull annotation on function generates unexpected result

### ISSUE THREAD

**Issue by husseinhere** [graphile/crystal#1595]
Test case:
```
CREATE TABLE tu(x bigint);
INSERT INTO tu(x) VALUES(1);
create function fu() returns tu as $$ select * from tu LIMIT 1 $$ language sql;
```

Now add a smart comment `@notNull` on the function, it makes `FuPayload` not null. But as mentioned in the last issue, the function throw an error so that is incorrect. So it should turn `CreateTuPayload { ..., tu: Tu, ... }` into `CreateTuPayload { ..., tu: Tu!, ... }` to show it can't return null

**Comment by benjie** [comment]
I’m inclined to agree 👍

**Comment by husseinhere** [comment]
And ideally there would be another annotation `@notThrows` which removes the top-level nullability
