### ISSUE TITLE
pgQuery for `field` returning `enum` fails

### ISSUE THREAD

**Issue by shellscape** [graphile/crystal#1601]
### Summary

I _think_ this is a bug. When we use `makeExtendSchema` to extend a type, and attempt to return an enum, we get the error:  `Error: @pgQuery(...) directive called with invalid arguments - for a table value, call it with 'source' for a scalar with 'fragment'!`

I'm having a hard time parsing this message, it's not very clear and could use some improvement. I also can't tell how it relates to my declaration below, or what the resolution is. Have we discovered a new bug?

### Steps to reproduce

We've got a TS enum defined as:

```ts
enum Severity {
  HIGH = 'HIGH',
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  NEUTRAL = 'NEUTRAL',
  OK = 'OK'
}
```

And the same declared in GraphQL:

```graphql
    enum Severity {
      OK
      NEUTRAL
      LOW
      MEDIUM
      HIGH
    }
```
 
With a field declared as:

```
      treeShakeableLevel: Severity! @pgQuery(
        fragment: ${embed(
          (queryBuilder: any) =>
            pgSql.fragment`(
              select
              (case when (select
                (
                  coalesce(_extra->'module', _extra->'jsnext:main') is not null
                    or
                  (_extra->'type' is not null and (_extra->'type')::text = 'module')
                )
                from
                  collectors.npm_versions v
                where
                  v.npm_package_id = ${queryBuilder.getTableAlias()}.id
                and
                  v.version = ${queryBuilder.getTableAlias()}.latest_version
                and
                  v.is_deleted = false
              ) = true then ${pgSql.literal(Severity.OK)} else ${pgSql.literal(Severity.NEUTRAL )} end)
            )`
        )}
      )
```

### Expected results

Server starts and creates schema successfully

### Actual results

`Error: @pgQuery(...) directive called with invalid arguments - for a table value, call it with 'source' for a scalar with 'fragment'!`

### Additional context

Of note, if we change `Severity!` to `String!` the server starts without issue.
Please let me know if you need any additional information or schema, resolver code, etc.

### Possible Solution

n/a

**Comment by benjie** [comment]
You’re probably right; we probably did an isScalarType check rather than isLeafType. Fancy hunting it down?

**Comment by shellscape** [comment]
Point me in the right direction and I'll give it a go. I've not worked with the repo source before so that would be helpful.

**Comment by shellscape** [comment]
Looks like the error message exists in the `graphile-engine` repo. I was able to get it to compile and run by adding:

`isLeafType` to  https://github.com/graphile/graphile-engine/blob/fb4b7f6c1680aa52105013b45b5f4a4639feb0ba/packages/graphile-utils/src/makeExtendSchemaPlugin.ts#L787

`const isLeaf = isLeafType(getNamedType(type));` to https://github.com/graphile/graphile-engine/blob/fb4b7f6c1680aa52105013b45b5f4a4639feb0ba/packages/graphile-utils/src/makeExtendSchemaPlugin.ts#L888

`(isScalar || isLeaf)` to https://github.com/graphile/graphile-engine/blob/fb4b7f6c1680aa52105013b45b5f4a4639feb0ba/packages/graphile-utils/src/makeExtendSchemaPlugin.ts#L1065

Not 100% sure that's working correctly since I'm getting a `"message": "Cannot return null for non-nullable field Package.treeShakeableLevel.",` when returning that field. But it does build and run without an error.

I leave the actual fix and test(s) in your wheelhouse.

**Comment by benjie** [comment]
Have added this caveat to the docs: https://github.com/graphile/graphile.github.io/commit/ea18be855f8db65a9d14dc3a4af622d501787cf7

**Comment by shellscape** [comment]
@benjie has this issue and associated fix been considered for v5?

**Comment by benjie** [comment]
I’ve not checked if v5 has this issue, but I doubt it does because it’s built in a completely different way.

**Comment by benjie** [comment]
No longer relevant because V5 works in a different way (and thus this issue almost certainly doesn't exist in V5).
