### ISSUE TITLE
Error highlighting and tooltips stopped working in Graphiql

### ISSUE THREAD

**Issue by rudism** [graphile/crystal#1655]
Running the built-in Graphiql used to provide error highlighting (red squiggles) and error tooltips against the graphql schema. It looked like this (this screenshot is from the [Graphiql live demo](http://graphql.org/swapi-graphql)):

![image](https://user-images.githubusercontent.com/4787751/181846284-456195a0-d6a6-44ee-bae0-ad072bf75bb2.png)

It seems at some point this stopped working in Postgraphile. To make sure it wasn't just my project, I ran through the [docker tutorial](https://www.graphile.org/postgraphile/running-postgraphile-in-docker/) and the error highlighting and tooltips don't work when I hit that Graphiql instance either:

![image](https://user-images.githubusercontent.com/4787751/181846050-ead77115-fc48-489e-a789-f454a12b28c4.png)

Autocomplete (and the explorer and docs when enabled) work OK, so the schema seems to be loading, it's just not doing the error highlighting or tooltips.

**Comment by benjie** [comment]
Unfortunately this was a bug in GraphiQL, but when it was fixed other updates to GraphiQL meant that we could not update to the new version without much effort. I'm focussed on PostGraphile V5 development currently (which has fixed this issue but has completely rebuilt PostGraphiQL in a non-backwards-compatible way) so this is certainly something someone else could take on of V4 but is not a priority for me.

**Comment by benjie** [comment]
This is fixed in [ruru](https://www.npmjs.com/package/ruru)
