### ISSUE TITLE
`createPostGraphileSchema` Documents the Entire Database

### ISSUE THREAD

**Issue by shellscape** [graphile/crystal#1663]
### Summary

I'm using `createPostGraphileSchema` to generate a cache for use with `readCache`.

```ts
await createPostGraphileSchema(pool, 'batman', opts);
```

The file that's generated contains information for the _entire_ database, not just the targeted schema. This puts the file well over 2MB. The target schema is extremely small, with three tables and three views. 

### Steps to reproduce

I've tried the snippet above on several schemas in our db and they all create a file with the entire db cache. 

### Expected results

A much smaller file with only information for the targeted schema.

### Actual results

Godzilla file.

### Additional context

Postgraphile v 4.12.11

**Comment by shellscape** [comment]
@benjie working with a company now that's considering sponsorship to access v5 early. what's the status/priority on getting the issues tagged with "revisit" resolved for v5?

**Comment by benjie** [comment]
Almost all the “revisit” issues are fixed in v5. This one you wouldn’t even do in v5, you just export the schema as executable code: https://dev.to/graphile/intro-to-postgraphile-v5-part-6-excellent-executable-exports-1150

**Comment by benjie** [comment]
V5 has been in open beta for a little while now; I'm closing this issue as resolved (though there is more work to be done to ensure that schemas are always exportable before we go to the final release).
