### ISSUE TITLE
No Nulls Array: [String!]!

### ISSUE THREAD

**Issue by ssendev** [graphile/crystal#1677]
### Summary

https://www.graphile.org/postgraphile/why-nullable/ doesn't mention arrays which can't contain nulls. 

I tried:
```sql
array text[] default '{}' not null check (array_position(array, null) is null)
```

but that doesn't change anything. 

With this plugin i was able to change the GraphQL type
```ts
export function NonNullArraysPlugin(builder: SchemaBuilder) {
  builder.hook('GraphQLObjectType:fields:field', (field, build, context) => {
    const {
      scope: { pgFieldIntrospection, isPgRowType },
    } = context
    const {
      graphql: { GraphQLNonNull, GraphQLList, isNonNullType, isListType },
    } = build

    if (
      isPgRowType &&
      pgFieldIntrospection.type.isPgArray &&
      pgFieldIntrospection.tags.noNullsArray
    ) {
      if (isNonNullType(field.type)) {
        const list = field.type.ofType
        if (isListType(list)) {
          const inner = list.ofType
          if (!isNonNullType(inner)) {

            return {
              ...field,
              type: GraphQLNonNull(GraphQLList(GraphQLNonNull(inner))),
            }
          }
        }
      }
    }
    return field
  })
}
```
but the no nulls constraint doesn't show up in `pgFieldIntrospection` or `pgIntrospection` is there a way to automatically detect it? 
If yes i think it would be possible to always add the inner non null since if row level constraints are present the whole row is null.

Then there is the sql codegen. Currently selecting an array generates this query
```sql
case when (__local_1__."array") is null then null when coalesce(
  array_length(
    (__local_1__."array"),
    1
  ),
  0
) = 0 then '[]'::json else (
  select json_agg(__local_2__)
  from unnest((__local_1__."array")) as __local_2__
) end
```
which is i guess the paranoid version to guarantee an empty array even when row level security denied access. Is it possible to tell postgraphile to assume it's always allowed and thus shorten the query to
```sql
to_json(__local_1__."array")
```
inside a `json_build_object` even the `to_json` could be omitted

### Additional context

postgraphile: 4.12.11
PostgreSQL: 14.5

**Comment by benjie** [comment]
I believe you can solve this with domains, like:

```sql
create domain non_null_text as text not null;

create table foo (
  array non_null_text[] not null default ARRAY[]::non_null_text[]
);
```

Alternatively you can use [`makeChangeNullabilityPlugin` in V5](https://postgraphile.org/postgraphile/next/make-change-nullability-plugin), which allows you to specify the nullability of any field or argument including the nullability of of list items.

**Comment by supersnager** [comment]
@benjie Your example does not work.

The following sql:

```sql
create domain app.non_null_text as text not null;

create table app.foo (
  array_field app.non_null_text[] not null default ARRAY[]::app.non_null_text[]
);
```
generates a type where element of an array is nullable
```graphql
type Foo {
  arrayField: [NonNullText]!
}
```
Is it possible to do something with this in v4?

The expected result is:
```graphql
type Foo {
  arrayField: [NonNullText!]!
}
```

**Comment by benjie** [comment]
Using a domain gives you a way to automatically detect it, you then need to hook it with a plugin. I think the domain trick probably already works without an extra plugin in v5 🤷‍♂️
