### ISSUE TITLE
Update to GraphiQL 2

### ISSUE THREAD

**Issue by byhemechi** [graphile/crystal#1705]
### Feature description

Update the version of `graphiql` used to version 2

### Motivating example

This is solely a quality-of-life change that i would assign very little weight on

graphiql 2 adds dark mode, tabs, and a different UI design to graphiql 1.x

### Supporting development

I [tick all that apply]:

- [ ] am interested in building this feature myself
- [x] am interested in collaborating on building this feature
- [x] am willing to help testing this feature before it's released
- [ ] am willing to write a test-driven test suite for this feature (before it exists)
- [ ] am a [Graphile sponsor](https://www.graphile.org/sponsor/) ❤️
- [ ] have an active [support or consultancy contract](https://www.graphile.org/support/) with Graphile

**Comment by benjie** [comment]
If you want to use GraphiQL v2 with PostGraphile-enhanced options, check out https://www.npmjs.com/package/ruru

(Installs fine with `yarn`, but you may need to put in a little effort if you use `npm`. It's pre-release software.)

PostGraphile V4 will not be upgrading to GraphiQL v2.

**Comment by benjie** [comment]
V5 comes bundled with Ruru which is our new version of PostGraphiQL, built on top of GraphiQL v2 :+1:
