### ISSUE TITLE
PgPool vs AWS RDS Proxies

### ISSUE THREAD

**Issue by sureshct** [graphile/crystal#1719]
### Summary
I am using postgraphile in a AWS Lambda environment to connect to postgreSQL.

While I am using Pg pool to handle the connections to PostgreSQL from Postgraphile, is there a need to use AWS RDS Proxies additionally ? 

So, basically, I am trying to understand the functional differences between PgPool vs RDS Proxies and how the connections can be effectively managed.

Thanks

**Comment by benjie** [comment]
🤷‍♂️

**Comment by Destreyf** [comment]
I haven't used RDS Proxy yet beyond some quick testing for a client.

The primary benefit to using RDS Proxy is that it'll handle load balancing among multiple reader nodes without having to reconfigure/restart your application, so if you add more reader nodes (read replicas), it should automatically distribute the connections among the instances.

Other than that, it appears to mainly be targeted at serverless deployments, offering quicker connection setups and acts as a pool itself where having to start a db connection/pool on every serverless invocation can have adverse perfromance characteristics.

I don't really know what the "magic" is that makes RDS Proxy better for serverless over a direct connection, but initial setup times were significantly better connecting to RDS Proxy over a direct connection to Amazon Aurora (Postgres).

In a non-serverless app, this initial connection setup time is quite trivial as it only happens upon startup/reconnection.
