### ISSUE TITLE
graphiql without external resources

### ISSUE THREAD

**Issue by stakaz** [graphile/crystal#1720]
I'm submitting a ... 

- [ ] bug report
- [ ] feature request
- [x] question 

I wounder if it is possible to enable graphiql interface but without external resources from unpkg.com and graphile.org.

Our organization disallows loading of external resources but we would like to provide the graphiql interface for our API.

Thanks

**Comment by benjie** [comment]
The external resources are optional - if not loaded they will degrade gracefully.

You may want to check out ruru, which is PostGraphile v5’s GraphiQL and is standalone and will be more configurable.
