### ISSUE TITLE
Relay preset filtering out enum tables

### ISSUE THREAD

**Issue by nick-kang** [graphile/crystal#1757]
### Summary

The Relay Preset filters out columns that are referencing enum tables.

### Expected results

Do not filter out foreign key enum columns.

### Possible Solution

I believe the bug is coming from.

https://github.com/graphile/crystal/blob/f649319a6fcc02eea3ca53097abfa29c27dc02df/postgraphile/postgraphile/src/presets/relay.ts#L104-L107

```typescript
          // suggested fix
          const isEnum = singularRelationsUsingThisColumn.some(
            (r) => r.remoteResource.extensions?.tags?.enum,
          )
          if (singularRelationsUsingThisColumn.length > 0 && !isEnum) {
            // Do not include this column in the schema (other than for create)
            newBehavior.push(...RELAY_HIDDEN_COLUMN_BEHAVIORS)
          }
```

**Comment by benjie** [comment]
Thanks for the catch! I rediscovered this myself just now by accident and remembered you had an issue for it, otherwise I would have spent a while scratching my head! :raised_hands:
