### ISSUE TITLE
Ability to add codecs via plugin system

### ISSUE THREAD

**Issue by drewwestphal** [graphile/crystal#1773]
### Feature description

It is currently not possible to add a custom scalar codec via the plugin system

### Motivating example

Working on a project that has columns of type ltree and mutation function parameters of type ltree

https://github.com/graphile/crystal/issues/1772
https://discord.com/channels/489127045289476126/1157342633644003429

### Supporting development

I [tick all that apply]:

- [ ] am interested in building this feature myself
- [x] am interested in collaborating on building this feature
- [x] am willing to help testing this feature before it's released
- [ ] am willing to write a test-driven test suite for this feature (before it exists)
- [x] am a [Graphile sponsor](https://www.graphile.org/sponsor/) ❤️
- [ ] have an active [support or consultancy contract](https://www.graphile.org/support/) with Graphile

**Comment by benjie** [comment]
Related: https://github.com/graphile/postgis/issues/58

**Comment by jsmnbom** [comment]
I'm currently using a hacky Plugin like this (and excluding the native "PgCodecsPlugin". But having this built in would definitely be very helpful ^^
https://gist.github.com/jsmnbom/67c3be9c30b1df96ce652b9c23741c0e

**Comment by benjie** [comment]
I'm getting back to V5 work again after a few months on other things (catching up, Worker, holidays, client work) and this is in my high priority list so leave it with me - I'll reach out if I can give some easy guidance.
