### ISSUE TITLE
Is there a way to make the Root Query not implement the Node interface?

### ISSUE THREAD

**Issue by psirenny** [graphile/crystal#1786]
My motivation is to allow for removing the `Query.id` field from the schema. I created a plugin to remove the field. Unfortunately, that breaks the schema because Query implements Node, which requires `id`.

I don't plan on supporting Relay v1, so having that field isn't needed in my case. That field also triggers a [@graphql-eslint/require-nullable-result-in-root](https://the-guild.dev/graphql/eslint/rules/require-nullable-result-in-root) ESLint error because the root ID field is non-optional.

**Note:** I should have mentioned that this is on PostGraphile V5!

**Comment by benjie** [comment]
Yep:

```ts
const preset: GraphileConfig.Preset = {
  disablePlugins: ['RegisterQueryNodePlugin'],
  // ...
};
```

Ref: https://github.com/graphile/crystal/blob/main/graphile-build/graphile-build/src/plugins/RegisterQueryNodePlugin.ts#L8-L10

(At least I think this is what does it; if not then ask again!)

**Comment by psirenny** [comment]
That makes sense, thanks for the fast response!

I tried disabling that plugin before albeit in a less elegant way 😅. When I do what you suggested it works exactly as I would have hoped. But then the exported schema breaks because it still references the removed field in a query extension:

```mjs
const Query_node_extensions = Object.assign(Object.create(null), {
  grafast: {
    plan(_$root, args) {
      return node(nodeIdHandlerByTypeName, args.get("id"));
    }
  }
});
```

Stack trace:

```shell
@spear-ai/underway-app:dev: [next:dev]  ⨯ ReferenceError: Cannot access 'nodeIdHandlerByTypeName' before initialization
@spear-ai/underway-app:dev: [next:dev]     at eval (webpack-internal:///(rsc)/./src/app/api/_postgraphile/exported-schema.mjs:1320:16)
@spear-ai/underway-app:dev: [next:dev]     at (rsc)/./src/app/api/_postgraphile/exported-schema.mjs (/Users/dtorres/Work/dev/spear-ai/underway/packages/underway-app/.next/server/_rsc_src_app_api__postgraphile_exported-schema_mjs.js:20:1)
@spear-ai/underway-app:dev: [next:dev]     at Function.__webpack_require__ (/Users/dtorres/Work/dev/spear-ai/underway/packages/underway-app/.next/server/webpack-runtime.js:33:43)
@spear-ai/underway-app:dev: [next:dev]     at async getGraphQLResponse (webpack-internal:///(rsc)/./src/app/api/_postgraphile/graphql.ts:32:24)
@spear-ai/underway-app:dev: [next:dev]     at async /Users/dtorres/Work/dev/spear-ai/underway/packages/underway-app/node_modules/@sentry/nextjs/cjs/common/wrapRouteHandlerWithSentry.js:50:32
@spear-ai/underway-app:dev: [next:dev]  ✓ Compiled in 664ms (1404 modules)
```

Is there another plugin I should be disabling as well?

**Comment by benjie** [comment]
That's for the `Query.node` field, which is part of the GraphQL Global Object Identification Specification. If you want to disable that (which will remove `Node` not just from `Query` but from everything, as well as removing the `Query.node` field) then add `'NodePlugin'` to the `disablePlugins` list.
