### ISSUE TITLE
Report of broken export relating to Global Object Identification

### ISSUE THREAD

**Issue by benjie** [graphile/crystal#1787]
> When I do what you suggested it works exactly as I would have hoped. But then the exported schema breaks because it still references the removed field in a query extension:
> 
> ```js
> const Query_node_extensions = Object.assign(Object.create(null), {
>   grafast: {
>     plan(_$root, args) {
>       return node(nodeIdHandlerByTypeName, args.get("id"));
>     }
>   }
> });
> ```
> 
> Stack trace:
> 
> ```shell
> @spear-ai/underway-app:dev: [next:dev]  ⨯ ReferenceError: Cannot access 'nodeIdHandlerByTypeName' before initialization
> @spear-ai/underway-app:dev: [next:dev]     at eval (webpack-internal:///(rsc)/./src/app/api/_postgraphile/exported-schema.mjs:1320:16)
> @spear-ai/underway-app:dev: [next:dev]     at (rsc)/./src/app/api/_postgraphile/exported-schema.mjs (/Users/dtorres/Work/dev/spear-ai/underway/packages/underway-app/.next/server/_rsc_src_app_api__postgraphile_exported-schema_mjs.js:20:1)
> @spear-ai/underway-app:dev: [next:dev]     at Function.__webpack_require__ (/Users/dtorres/Work/dev/spear-ai/underway/packages/underway-app/.next/server/webpack-runtime.js:33:43)
> @spear-ai/underway-app:dev: [next:dev]     at async getGraphQLResponse (webpack-internal:///(rsc)/./src/app/api/_postgraphile/graphql.ts:32:24)
> @spear-ai/underway-app:dev: [next:dev]     at async /Users/dtorres/Work/dev/spear-ai/underway/packages/underway-app/node_modules/@sentry/nextjs/cjs/common/wrapRouteHandlerWithSentry.js:50:32
> @spear-ai/underway-app:dev: [next:dev]  ✓ Compiled in 664ms (1404 modules)
> ```

See https://github.com/graphile/crystal/issues/1786#issuecomment-1747745176

Reported by @psirenny

**Comment by romeovs** [comment]
A similar error also occurs in the `schema-export-output.mjs` file generated by [`graphile-build-pg/src/examples/schema-export.ts`](https://github.com/graphile/crystal/blob/main/graphile-build/graphile-build-pg/src/examples/schema-export.ts) for the `pagila` dataset mentioned in the README.

**Comment by benjie** [comment]
I suspect this will be fixed by the next release; if it isn't then please reopen.

**Comment by benjie** [comment]
Reported to still be an issue.

**Comment by benjie** [comment]
Fixed in https://github.com/graphile/crystal/pull/1946 with detection added for similar issues.

**Comment by nckswt** [comment]
Confirming that it's been fixed for me. Thanks!
