### ISSUE TITLE
@name ignored for native enums

### ISSUE THREAD

**Issue by innermatrix** [graphile/crystal#1795]
### Summary

`@name` is ignored on native Postgres enums in v5 (it was working in v4)

### Steps to reproduce

```
create type e as enum ('E1');
comment on type e is '@name f';

create table t(c1 e);
```

### Expected results

```
enum F {
  E1
}
```

### Actual results

```
enum E {
  E1
}
```

### Additional context

```
export default  {
    extends: [PostGraphileAmberPreset],
    pgServices: [
		makePgService({
			connectionString: process.env.DATABASE_URL,
			schemas: ['public'],
		}),
	],

}
```

crystal @ f4159ba7aa9978dc57537283f6f8cb828de0fe8d

**Comment by benjie** [comment]
Turns out the tags just literally weren't copied onto the codec. Resolved.
