### ISSUE TITLE
Mistakes in documentation

### ISSUE THREAD

**Issue by Igorgro** [graphile/crystal#1800]
### Summary

I'm trying to run beta version of Postgraphile and have encountered with some mistakes in documentation. First, the example of starting server on https://postgraphile.org/postgraphile/next/usage-library not completely correct and this is how I it works in typescript:
```typescript
import { createServer } from "node:http";
import postgraphile from "postgraphile";
import { grafserv } from "grafserv/dist/servers/express/v4"; // <- Notice this
import express from 'express';

import preset from "./graphile.config";

export const pgl = postgraphile(preset);
const serv = pgl.createServ(grafserv);


const app = express();
const server = createServer(app);
server.on("error", () => {});
serv.addTo(app, server).catch((e) => {
  console.error(e);
  process.exit(1);
});
server.listen(5678);

console.log("Server listening at http://localhost:5678");
```
this is caused by the fact that grafserv has no direct exports, so that it must be imported from `dist` directory.
The second problem is with configuration. I tried to set configuration according to https://postgraphile.org/postgraphile/next/config, but here I encountered the same problem and this is how my config looks like:
```typescript
import "graphile-config";
import "postgraphile";

import { PostGraphileAmberPreset } from "postgraphile/dist/presets/amber"; // <- again, a dist

const preset: GraphileConfig.Preset = {
  extends: [PostGraphileAmberPreset],
};

export default preset;
```
then I tried to connect to Postgres database, which should be done using 'makePgService' function, but I have looked through all the `postgraphile` package and haven't found where I can import this function from.

**Comment by Igorgro** [comment]
Ok, I found that I should setup "esnext" in tsconfig.json to make this work.

**Comment by Igorgro** [comment]
Now I managet to finally start Postgraphile, but the generated chema is empty in contains only 'Node' interface and the 'Query' type

**Comment by benjie** [comment]
Node shouldn’t even let you import from dist; glad you found the TypeScript requirements: https://postgraphile.org/postgraphile/next/requirements#typescript-v500-optional

If your GraphQL schema is empty it suggests you are either connected to the wrong database, have specified the wrong schema list, or are using a role in the connection string that has insufficient privileges. I’d ask in the Discord at https://discord.gg/graphile; hopefully someone there can help you diagnose and solve the issue.

**Comment by Igorgro** [comment]
@benjie yes, it was the permissions problem and I temporarily solved it by switching to superuser 'postgres', but the user which I used to connect is the owner of connected database and this is not sufficent, so what additional permission should it have?
