### ISSUE TITLE
How to wait for initial schema load from DB in watch mode

### ISSUE THREAD

**Issue by benweint** [graphile/crystal#1805]
Hello! My team has been experimenting with the Postgraphile v5 betas. We're using 'watch mode' (`watch: true` in the [grafserv options](https://postgraphile.org/postgraphile/next/config#grafserv-options)), and finding that if we issue an introspection query immediately after the server comes up, it shows that only a 'base' empty GraphQL schema is available, with none of the types discovered from Postgres. Shortly after this, the schema is updated automatically to include the fields derived from DB introspection.

We'd like to be able to use watch mode, but also wait for at least the *first* database introspection + schema building pass to complete before we begin sending requests. Is there any way to do this in Postgraphile v5 at present?

**Comment by benjie** [comment]
This _shouldn't_ be the case. Please can you try on the very latest release of V5 which went out today, and report back if this issue still exists?

**Comment by benweint** [comment]
I think this was some kind of oddity of our setup, because I'm no longer able to reproduce it after we made some changes out our DB connection setup (even before upgrading to the latest version). Closing this for now, and will re-open with actual repro steps if we see it again!
