### ISSUE TITLE
Get context in `grafserv.maskError`

### ISSUE THREAD

**Issue by eugeneduda** [graphile/crystal#1811]
### Feature description

It'll be usefull to have an ability to get `Grafast.Context` in the `GraphileConfig.GrafservOptions.maskError`. For instance:

```ts
grafserv: {
    ...
    maskError: (err, context) => {
        ...
     }
  },
 ```

### Motivating example

This can be useful for errors logging. For example:

```ts
grafserv: {
    ...
    maskError: (err, { userId }) => {
       if (e.originalError instanceof db.NotExactlyOneError) {
           logger.warn(
             "Attempting to access a prohibited or non-existent resource",
             userId
           );
       }
       return e;
     }
  },
 ```

### Supporting development

I [tick all that apply]:

- [ ] am interested in building this feature myself
- [ ] am interested in collaborating on building this feature
- [ ] am willing to help testing this feature before it's released
- [ ] am willing to write a test-driven test suite for this feature (before it exists)
- [ ] am a [Graphile sponsor](https://www.graphile.org/sponsor/) ❤️
- [ ] have an active [support or consultancy contract](https://www.graphile.org/support/) with Graphile

**Comment by benjie** [comment]
Regular graphql errors should not have reached your generic handler in v4, only critical errors which meant we failed to handle the request at all.

We don’t yet have the hook system in place for error logging; maskError isn’t really the right place (unless the logging specifically relates to the masking, as in the default implementation) but there is currently no other place. This is one of many many things that we need to address before we can promote v5 from the “beta” phase.

**Comment by benjie** [comment]
It seems that this is too challenging to achieve whilst keeping support for all the different potential servers, for example `graphql-ws` has an `onError` callback that I can't figure out how to get the context from. I'm going to close it for now, sorry.
