### ISSUE TITLE
Bundling error when used with NextJS

### ISSUE THREAD

**Issue by tim-field** [graphile/crystal#1826]
### Summary

Unable to import postgraphile (v5) or grafast in an next js project.

Attempting to setup a route that includes postgraphile v5 but next refuses to bundle

```
 ⚠ ./node_modules/graphile-build-pg/dist/pgServices.js
Critical dependency: the request of a dependency is an expression        

Import trace for requested module:
./node_modules/graphile-build-pg/dist/pgServices.js
./node_modules/graphile-build-pg/dist/index.js
./node_modules/postgraphile/dist/index.js
./src/lib/graphile/pgl.ts
./src/app/graphql/route.ts
```

```
//pgl.ts
import preset from './graphile.config'
import postgraphile from 'postgraphile'

export const pgl = postgraphile(preset)
```

### Steps to reproduce

Create a new next js app using `npx create-next-app@latest `

install  postgrahile@beta I was using `^5.0.0-beta.15`

Attempt to setup a route which imports postgraphile

### Expected results

Next js able to complile / bundle

### Actual results

A bundling error

### Additional context

@benjie thinks this is a bundling error 

> It’s a bundling issue; I’m afraid I’ve not put time into supporting that yet. Please file an issue with the above details; it sounds like I’ll need to change the configuration format to avoid a dynamic require

https://discord.com/channels/489127045289476126/1165551144299401317/1165574782675329056

![image](https://github.com/graphile/crystal/assets/1326910/05510b6c-8cfe-410e-a6af-4bf15f031b7c)

**Comment by benjie** [comment]
Relates to #1985

**Comment by psirenny** [comment]
@tim-field did you find a workaround to this issue?

**Comment by psirenny** [comment]
We're working around the issue by marking dependencies as external:

```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  experimental: {
    esmExternals: true,
    serverComponentsExternalPackages: [
      "grafast",
      "grafserv",
      "graphile-export",
      "graphql",
      "postgraphile",
      "ruru",
    ],
  },
};
```

**Comment by AbelGuitian** [comment]
@benjie I'm getting next build errors with postgraphile v4 as well, If I do as @psirenny is doing, the error on runtime disappear but some other weird logs show up. Is there a way to apply the fix you included in postgraphile v5?
