### ISSUE TITLE
whitespace between column names in ref causes Error: Invalid parameter name crash

### ISSUE THREAD

**Issue by wesselvdv** [graphile/crystal#1836]
### Summary

When defining a @ref like this:

```
@ref typeA via:(id_1,id_2)->types_a.a(id_1, id_2) singular
```

Causes the following crash:

```
Error occurred whilst building the schema (phase = GATHER; attempt 1). We'll try again in 100ms.
  Error: Invalid parameter name
```

Where as removing the white space between the id_1 and id_2 like so:

```
@ref typeA via:(id_1,id_2)->types_a.a(id_1,id_2) singular
```

Seems to work fine.

### Steps to reproduce

Add a @ref comment with spaces between the column fields. (e.g. `column_1, column_2`)

### Expected results

I expect it to work with or without spaces after the comma between columns.

### Actual results

It crashes when spaces are between the column fields.

**Comment by benjie** [comment]
Smart tag parameters work like `key:value`, `key:"value with spaces"`, or just `key` for parameters with no values. If you need to include a space in your parameter value (in this case for the value of the `via` key) then you need to wrap the value in quotes:

```
@ref typeA via:"(id_1,id_2)->types_a.a(id_1, id_2)" singular
```

I suppose we _could_ add a parenthesis counter to the smart tags parameters parser (`parseSmartTagsOptsString` in `graphile-build/graphile-build-pg/src/utils.ts`) but that seems a bit special to me, and would invalidate things like:

```
@sometag openChar:( closeChar:)
```

Though arguably it would be less visually confusing for that to be this instead:

```
@sometag openChar:"(" closeChar:")"
```

So I'm open to it.

**Comment by benjie** [comment]
I've gone ahead and written the changes to the parser in #1841; we'll see what CI thinks of it.

**Comment by benjie** [comment]
#1841 solves the error above, but doesn't necessarily mean that the refs parser can then parse the path. Hopefully it can, but I've not checked.
