### ISSUE TITLE
Description ignored on enums

### ISSUE THREAD

**Issue by innermatrix** [graphile/crystal#1840]
### Summary

Description on enum not copied from SQL comment to gql schema 

### Steps to reproduce

```
create type
e as enum('A', 'B');

comment on
type e is E'@name F
G';

create table t(c e);
```

### Expected results

```
"""G"""
enum F {
  A
  B
}
```

### Actual results

```
enum F {
  A
  B
}
```

### Additional context

Graphile @ 3df4bc53de8210c11223cf03a27646374240b8ec

**Comment by benjie** [comment]
Theoretically the description makes it here?

https://github.com/graphile/crystal/blob/main/graphile-build/graphile-build-pg/src/plugins/PgCodecsPlugin.ts#L581

Looks like it's not being added here:

https://github.com/graphile/crystal/blob/34a85f28b1a950b2290f57d29ea258f1a61207f1/graphile-build/graphile-build-pg/src/plugins/PgCodecsPlugin.ts#L1156 

If you want to take this on, look at where similar types are registered in this file with descriptions and copy that here. Should be a line or two of code.
