### ISSUE TITLE
Rename condition types

### ISSUE THREAD

**Issue by yukukotani** [graphile/crystal#1844]
### Summary

Is there any way to rename `XxxCondition` type?

I have many pair of `foo` and `foo_condition` table and the generated types conflict. I know that I can rename `foo_condition` table using smart tag, but I want to rename the condition of `foo` table since it's hard to rename a lot of tables.

It would be nice if I could specify prefix or suffix of automatically generated condition types.

**Comment by benjie** [comment]
Yes; use [inflection](https://postgraphile.org/postgraphile/next/inflection/):

```ts
export const RenameConditionPlugin: GraphileConfig.Plugin = {
  name: "RenameConditionPlugin",
  inflection: {
    replace: {
      conditionType(prev, options, typeName) {
        return this.upperCamelCase(`prefix-${typeName}-suffix`);
      },
    },
  },
};
```

**Comment by yukukotani** [comment]
Cool. Thanks!
