### ISSUE TITLE
Ruru explorer inputs are truncated when entered rapidly

### ISSUE THREAD

**Issue by jvandermey** [graphile/crystal#1845]
### Summary

When entering input via the explorer pane in Ruru, keystrokes are often overwritten resulting in only the last character being persisted.

### Steps to reproduce

1. Write a query that accepts input via the explorer pane
2. Enter input into the explorer rapidly

### Expected results

All keystrokes are persisted in the input

### Actual results

Some characters are overwritten by subsequent keystrokes.

### Additional context

This occurs with the unmodified ruru configuration, but is not present when running the stock graphiql explorer as configured in [this repo](https://github.com/OneGraph/graphiql-explorer-example).

In the attached video, I attempted to type `this is missing input`.

[Screencast from 11-02-2023 01:49:38 PM.webm](https://github.com/graphile/crystal/assets/7964026/631d45e8-ad44-4c1b-a739-b239731c3e8a)

**Comment by jvandermey** [comment]
There is no issue when entering text directly in the editor pane.

**Comment by benjie** [comment]
This is most likely a bug in GraphiQL Explorer; but it does look like we're using an older version...

**Comment by benjie** [comment]
Opened a PR upstream: https://github.com/graphql/graphiql/pull/3526
