### ISSUE TITLE
Cannot find module '@dataplan/pg/adaptors/pg' after the app is bundled 

### ISSUE THREAD

**Issue by MarioSimou** [graphile/crystal#1855]
### Summary

I started using postgraphile@v5 on a project of mine, where I am using `tsup` and `esbuild` to bundle the app. When the bundling is done and try to run the app, I get this error `Cannot find module '@dataplan/pg/adaptors/pg' `. When I remove the import related to the pg adaptor in my source code, re-bundle the app and run it again, it works fine. I tried to follow the [doc](https://postgraphile.org/postgraphile/next/bundling-webpack/) here, making a few adjustments how I bundle the app, but the issue persists. Can you help me solve this issue?

![failure](https://github.com/graphile/crystal/assets/32243459/f2967936-af17-4c70-be02-8c821eee3208)

Here is a reference of my `tsup.config.ts`

```
import {defineConfig} from 'tsup'
import {dependencies} from './package.json'

export default defineConfig({
  entry: ['./src/**/*.ts'],
  platform: 'node',
  format: 'esm',
  clean: true,
  splitting: true,
  skipNodeModulesBundle: false,
  treeshake: true,
  bundle: true,
  sourcemap: false,
  banner: {
    js: `
    import {fileURLToPath as topLevelFileUrlToPath} from 'url';
    import {dirname as topLevelDirname} from 'path';
    import { createRequire as topLevelCreateRequire } from 'module';
    const require = topLevelCreateRequire(import.meta.url);
    const __filename = topLevelFileUrlToPath(import.meta.url);
    const __dirname = topLevelDirname(__filename);
    `,
  },
  // If keepNames is disabled, the app fails with: `Error: GraphQL conflict for 'e'
  // detected! Multiple versions of graphql exist in your node_modules?`
  minify: false,
  keepNames: false,
  terserOptions: {
    keep_classnames: false,
  },
  define: {
    'process.env.NODE_ENV': '"production"',
    'process.env.GRAPHILE_ENV': '"production"',
    // 'process.env.NODE_PG_FORCE_NATIVE': '"1"',
    // 'process.env.POSTGRAPHILE_OMIT_ASSETS': '"1"',
    // 'process.env.GRAPHILE_OMIT_ASSETS': '"1"',
  },
  noExternal: Object.keys(dependencies),
})
```

### Steps to reproduce

1. Install postgraphile in a project that uses `tsup`.
2. Create `graphile.config.ts` and set the definition of your preset. Make sure to use `makePgService`, which uses pg adaptor internally.
3. Bundle the app.
4. Try to run it. You should get this error.  

### Expected results

Run the app without any issues.

### Actual results

The app fails to run.

### Additional context

I am using `node@v18` on `Linux Ubuntu 20.04.6 LTS`

**Comment by benjie** [comment]
Sorry; I don't have the bandwidth to debug bundling issues for you; any issues like this where you can run the code directly fine but the bundle causes an issue is seen by me as a bug in either the bundler or your configuration of the bundler.

One suggestion though, try changing `@dataplan/pg/adaptors/pg` to `postgraphile/@dataplan/pg/adaptors/pg`

**Comment by MarioSimou** [comment]
I am happy to debug it myself, but I need some help. I tried importing the pg adaptor using `postgraphile/@dataplan/pg/adaptors/pg`, `postgraphile//adaptors/pg` and `postgraphile/@dataplan/pg/adaptors/pg`. None of those worked. Is there an different adaptor that I can test?

Also, is there anything in my tsup config which may be wrong and catches your attention?

**Comment by benjie** [comment]
I have never once use `tsup` so can't help there.

If it works in Node and fails with `tsup` then maybe you should ask for help from `tsup`?

**Comment by nckswt** [comment]
Just noting that I've also tried transitioning to v5 (because I need to support graphql 16) and have encountered the exact same issue. Just started the debugging route, but wanted to note the heightened barrier to entry. (Thanks for developing this regardless -- very excited to use it, especially after seeing the hard work going into v5!)

**Comment by benjie** [comment]
@nckswt Are you also using `tsup` and `esbuild`? If so, someone using these technologies should probably work with them to have them support the node standard `exports` property; ref:

- https://nodejs.org/api/packages.html#exports
- https://nodejs.org/api/packages.html#package-entry-points
- https://nodejs.org/api/packages.html#subpath-exports

**Comment by benjie** [comment]
(If not, then perhaps file a different issue with more details.)

**Comment by nckswt** [comment]
Thanks for the quick feedback! I'm not using `tsup` or `esbuild`, but `tsc` directly and running via `npx ts-node -P tsconfig.es.json tools/generateSchema.ts`. 

I'll poke around a bit, as it's likely an issue with my setup, but I'll create an issue if I find any upstream issues. For reference, here's the exact import errors (noting that I'm grabbing `postgraphile/adaptors/pg` instead of OP's `@dataplan/pg/adaptors/pg`) :

```tools/generateSchema.ts:7:31 - error TS2307: Cannot find module 'postgraphile/adaptors/pg' or its corresponding type declarations.

7 import { makePgService } from "postgraphile/adaptors/pg";
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~
tools/generateSchema.ts:8:41 - error TS2307: Cannot find module 'postgraphile/presets/amber' or its corresponding type declarations.

8 import { PostGraphileAmberPreset } from "postgraphile/presets/amber";
```

**Comment by benjie** [comment]
Oh good, that’s a one line fix; you need to tell TypeScript to support the Node standard exports property which you do using the moduleResolution setting as detailed in the docs: https://postgraphile.org/postgraphile/next/requirements#typescript-v500-optional

**Comment by nckswt** [comment]
That works! Thanks! I must've missed that.

**Comment by benjie** [comment]
@nckswt Perhaps you'd consider sending a PR to that file with the errors you received so people who search for the issue will hit that part of the docs? All docs pages have an edit link that'll guide you through raising a PR :+1:
