### ISSUE TITLE
Postgraphile v5 plugin error

### ISSUE THREAD

**Issue by roland-pep** [graphile/crystal#1862]
### Summary

I'm trying to migrate from postgraphile v4 to v5, and I did hit an issue with the plugins.
I tried using PgSimplifyInflector and ConnectionFilter, but the same problem, which is the following:

```
Error: Error occurred when resolving preset: Error: Expected plugin, but found '[Function: PostGraphileConnectionFilterPlugin]'
Preset: {
  extends: [ { extends: [Array], plugins: [Array] } ],
  plugins: [
    [Function: PostGraphileConnectionFilterPlugin],
    <ref *1> [Function: PgSimplifyInflectorPlugin] {
      default: [Circular *1]
    } 
  ], ....
```
As a reference, I import them as following:
```
import ConnectionFilterPlugin from "postgraphile-plugin-connection-filter";
import PgSimplifyInflectorPlugin from "@graphile-contrib/pg-simplify-inflector";
```

**Comment by benjie** [comment]
Please be sure you're using `postgraphile-plugin-connection-filter@beta` - that's the V5 version of that preset.

Please be sure you're using `@graphile/simplify-inflection@beta`.

Please consult https://github.com/benjie/ouch-my-finger for an example.
