### ISSUE TITLE
Comments on computed column functions are not present in the resulting GraphQL schema

### ISSUE THREAD

**Issue by enisdenjo** [graphile/crystal#1887]
```sql
CREATE FUNCTION person_full_name(person person) RETURNS text AS $$
  SELECT person.given_name || ' ' || person.family_name
$$ LANGUAGE sql STABLE;

COMMENT ON FUNCTION person_full_name IS 'The full name of this person.';  -- 👈
```

The `Person.fullName` field does not have the "The full name of this person." comment.

**Comment by enisdenjo** [comment]
This is not true. See tests in #1890.

**Comment by benjie** [comment]
Could be that you had a `COMMENT ON FUNCTION` later on which overwrote this?

**Comment by enisdenjo** [comment]
I might've been looking at the Patch or Condition types instead of the actual belonging type. 🤔
