### ISSUE TITLE
Enums not matched in postgraphile.tags.json5

### ISSUE THREAD

**Issue by tinleym** [graphile/crystal#1900]
### Summary

Enums are not matched in postgraphile.tags.json5 (though I'm _not_ having the same issue attaching tags via comments)

### Steps to reproduce

1) Create an enum in Postgres
2) Reference said enum in postgraphile.tags.json5 under `class`

### Expected results

Enum will be found and matched

### Actual results

Enum not matched: `WARNING: there were no matches for makePgSmartTagsPlugin rule 14 -  ...`

**Comment by benjie** [comment]
An enum is not a class (a table-like thing), it's a type.

Please share the comment syntax you're trying too.

**Comment by tinleym** [comment]
Eek, I left the "not" out of `though I'm _not_ having the same issue attaching tags via comments`. That's all good.

**Comment by benjie** [comment]
So if you use `type` instead of `class` for the `postgraphile.tags.json5` does the issue go away? Please share both the `postgraphile.tags.json5` file and the smart comment you're using.

**Comment by tinleym** [comment]
Ah, I wasn't aware of the type field! That solves it.
