### ISSUE TITLE
Set bodySizeLimit for graphile v5

### ISSUE THREAD

**Issue by 1mehal** [graphile/crystal#1918]
### Summary
I'm using v5 and faced a need to increase bodySizeLimit, wasn't able to do so using a library

```
const preset: GraphileConfig.Preset = {
	extends: [PostGraphileAmberPreset],
	pgServices: [
		makePgService({
			connectionString,
			schemas: ['app_public']
		})
	],
	grafast: {
		context(requestContext, args) {
			return {
				pgSettings: {
					...args.contextValue?.pgSettings,
				}
			};
		}
	},
	schema: {}
};

export const pgl = postgraphile(preset);
const serv = pgl.createServ(grafserv);
```

I would expect a way to specify a http body limit, so my queries would pass thru 

I've found an option at grafast : _maxRequestLength_ but wasn't able to find the way hot to incorporate it in code above

**Comment by benjie** [comment]
It’s preset.grafserv.maxRequestLength:

https://github.com/graphile/crystal/blob/main/grafast/grafserv/src/index.ts#L107

This isn’t in the greater docs, so a PR there would be welcome.

**Comment by 1mehal** [comment]
@benjie I've tried to set that preset, but it still failed with the same message, I would try again and report here

**Comment by benjie** [comment]
Note: `grafserv` not `grafast`; if it doesn’t work please share your latest config.
