### ISSUE TITLE
pg-introspection doesnt seem to provide a way to detect index type or index options

### ISSUE THREAD

**Issue by DanielFGray** [graphile/crystal#1925]
### Feature description

using `pg-introspection` I would like to find out what options[/expressions?] an index was created with, eg whether it is a btree or gin or gist index and whether it has options like `gin_trgm_ops`

### Motivating example

I'm currently working on a tool that does code generation based on results from pg-introspection, and I think having this feature would enable to make some interesting features

### Breaking changes

I don't believe this enhancement would constitute a breaking change

### Supporting development

I [tick all that apply]:

- [ ] am interested in building this feature myself
- [x] am interested in collaborating on building this feature
- [x] am willing to help testing this feature before it's released
- [ ] am willing to write a test-driven test suite for this feature (before it exists)
- [x] am a [Graphile sponsor](https://www.graphile.org/sponsor/) ❤️
- [ ] have an active [support or consultancy contract](https://www.graphile.org/support/) with Graphile

**Comment by benjie** [comment]
Frustratingly I've not got around to extracting and tidying up the code that generates `pg-introspection` yet (it's currently part of the https://pgrita.com codebase) so this isn't something we can collaborate on yet. I've added it as high priority to [my V5 list](https://github.com/orgs/graphile/projects/3).
