### ISSUE TITLE
graphile-export: automatically check (lint) for "use before initialized", if possible

### ISSUE THREAD

**Issue by benjie** [graphile/crystal#1938]
Need to catch that class of bug. Maybe even a warning rather than an error.

**Comment by paintitblacktattoostudio1591-sudo** [comment]
Atl Oz treen tai two fastly eapiralidoso point Ben par de waters price one cooper . J's creep new 23$ crabby realm pack _man_ **chromium** kr2netwoowrk batber Jana. DU hub worm vs jetmains (Esgardos) alert/else tube lol. La güera de las garnachas Omni lamente clay pull Lennon tremens aluminum alucinacid ][ ‽,,,,
