### ISSUE TITLE
eval is evil (and undocumented)

### ISSUE THREAD

**Issue by benjie** [graphile/crystal#1950]
Ref: https://discord.com/channels/489127045289476126/498852330754801666/1205068909787746304

> So apparently the eval methods are completely undocumented... Good to know.
> 
> Yes; all the eval methods have a cost, but the more specific you can be the better. `.evalHas(key)` causes the plan to branch such that `.evalHas('foo')` will have two versions of the plan - one where foo is present, and one where foo is not present. (Compare to `.eval()` where each individual different object will result in a new plan.)
>
> `$__inputStep.evalHas(key)`: two plans
> `$__inputStep.eval()`: almost infinite plans
> `$__inputStep.evalLength()`: one plan for each length of the list
> `$__inputStep.evalIs(val)`: two plans (one where $__inputStep's value `=== val`; and one where it doesn't)

**Comment by benjie** [comment]
Actually, we're looking to maybe remove eval if we can... So let's put this on ice.

**Comment by jemgillam** [comment]
how does tamedeval relate to eval() ?

**Comment by benjie** [comment]
`eval()` in JS evaluates a string as code.

`tamedevil` makes it easier to work with `eval()` in a safe way.

In Grafast, input steps have an `.eval()` (or `.evalIs()`, `.evalHas()`, etc) method. This is **unrelated** to JS's `eval()` and thus to `tamedevil`; it only relates to evaluating the real value of this step during planning (and means that the plan is only valid for future requests where the evaluated value or expression matches).

**Comment by jemgillam** [comment]
> [@jemgillam](https://github.com/jemgillam) I think details of this was in one of the sponsors only talks; perhaps you could extract it and add to the docs?

Hmmm I think I don't have access to those videos, I guess it was a Discord event? I can say you didn't cover it in the working groups we've done or the 2022 onboarding.

**Comment by jemgillam** [comment]
Closed with #2213
