### ISSUE TITLE
Detect computed columns from public schema

### ISSUE THREAD

**Issue by GeertJohan** [graphile/crystal#1959]
### Feature description

We're running a fairly large database that uses a lot of computed columns already. We used to place these in the public schema, so that any SQL query can reference the computed columns.

For example:
```
public.full_reference(order sales.orders) text
public.full_reference(job work.jobs) text

SELECT orders.full_reference FROM sales.orders;
SELECT jobs.full_reference FROM work.jobs;
```

I'm wondering if graphile can also detect these columns. Perhaps behind a feature gate (disabled by default to not break existing users), or as a plugin that can be implemented by graphile users..

### Supporting development

I [tick all that apply]:

- [ ] am interested in building this feature myself
- [x] am interested in collaborating on building this feature
- [x] am willing to help testing this feature before it's released
- [ ] am willing to write a test-driven test suite for this feature (before it exists)
- [ ] am a [Graphile sponsor](https://www.graphile.org/sponsor/) ❤️
- [ ] have an active [support or consultancy contract](https://www.graphile.org/support/) with Graphile

**Comment by benjie** [comment]
In v5 you would add the +typeField behaviour to the function and it should Just Work ™️ 

`comment on function … is '@behavior +typeField';`

**Comment by GeertJohan** [comment]
Wow that sounds amazing! Looking forward to it, thanks @benjie !

**Comment by benjie** [comment]
(You can use it now; PostGraphile V5 is in open beta.)
