### ISSUE TITLE
Release fix for postgraphile-plugin-connection-filter export schema 

### ISSUE THREAD

**Issue by nckswt** [graphile/crystal#1975]
Based on [discord chat](https://discord.com/channels/489127045289476126/498852330754801666/1212191648604364845), filing this issue to make all required functions from https://github.com/graphile-contrib/postgraphile-plugin-connection-filter exportable (see [this PR](https://github.com/graphile-contrib/postgraphile-plugin-connection-filter/pull/207))

**Comment by benjie** [comment]
Released in `postgraphile-plugin-connection-filter@3.0.0-beta.3`

**Comment by nckswt** [comment]
Awesome -- thanks @benjie!
