### ISSUE TITLE
How to join the tables in database using postgraphile?

### ISSUE THREAD

**Issue by Prabhanjali** [graphile/crystal#1981]
### Summary
I have a cloudquery postgress DB for which we have multiple tables for each resource type.
I want to join these tables to get all details for a single resource. 

For example, I am having 3 different tables like ec2_metadata, ec2_instances, ec2_instance_types. Internally, how to connect all these tables and join them (like join ec2_metadata and ec2_instance_types (or) ec2_instances and ec2_instance_types). 

Also, to join the tables in postgraphile do we actually require foreign key relationship?

**Comment by benjie** [comment]
> Also, to join the tables in postgraphile do we actually require foreign key relationship?

You can use foreign key constraints, or you can use "fake constraints" like the `@foreignKey` smart tag: https://postgraphile.org/postgraphile/next/smart-tags#foreignkey

For details on relationships:

https://postgraphile.org/postgraphile/next/relations
