### ISSUE TITLE
website: things to do before deployment

### ISSUE THREAD

**Issue by jemgillam** [graphile/crystal#2007]
I have a suspicion some things need sorting out before we deploy the postgraphile.org site: 

- move the fontawesome dependencies to `devDependencies` like in https://github.com/graphile/worker/pull/444/
- I think @benjie mentioned the nested styling is actually broken, I can't remember the fix we discussed, or how I can reproduce this on my machine

**Comment by benjie** [comment]
Also it documents the new APIs which can't go out until the latest @beta is published.

**Comment by benjie** [comment]
Relates to this PR: https://github.com/graphile/crystal/pull/1964

**Comment by benjie** [comment]
Fixed in https://github.com/graphile/crystal/commit/176f6ddff79079ccc399d5d65626c5ea698c36c1
