### ISSUE TITLE
How to add condition for a table that is related to other(while joining tables)

### ISSUE THREAD

**Issue by Prabhanjali** [graphile/crystal#2009]
### Summary
We have two tables AAAA and BBBB. Now I am trying to joining AAAA with BBBB and getting some data based on conditions

```graphql
{
  AAAA(filter: {ab: {isNull: false}}) {
    nodes {
      id
      BBBB{
        type
      }
    }
    totalCount
  }
}
```

Here I need to add a condition where my type is "ccdd" in table BBBB

**Comment by benjie** [comment]
This is more a question for the filter plugin, but something like this:

```graphql
{
  AAAA(filter: {ab: {isNull: false}, BBBB: { type: { isEqual: "ccdd" } }}) {
    nodes {
      id
      BBBB{
        type
      }
    }
    totalCount
  }
}
```

You need to turn on relational filters; see: https://github.com/graphile-contrib/postgraphile-plugin-connection-filter?tab=readme-ov-file#connectionfilterrelations

**Comment by Prabhanjali** [comment]
What should be the version of the postgraphile for this filter to work?

This filter is not working in this version 
 "postgraphile": "^4.13.0",
  "postgraphile-plugin-connection-filter": "^2.3.0"

**Comment by benjie** [comment]
Any release from the last couple years should work; do make sure you read the filter plugins documentation though - especially the part I mentioned above about enabling relational filters.

**Comment by Prabhanjali** [comment]
This is not working for me, 
![image](https://github.com/graphile/crystal/assets/79193434/82b3316c-ea37-4e89-a6f6-7edc365ed0b7)
I am getting the above error.

I have added this **connectionFilterRelations: true**. But still it is not working
Can you please let me know what is causing the issue?

**Comment by benjie** [comment]
Seems like you’re querying field 🟥🟥🟥🟥 on type 🟥🟥🟥🟥, but that field doesn’t exist. You should use GraphiQL or similar to build your query so it will show you what’s wrong.

**Comment by Prabhanjali** [comment]
This is the query I am using
```
{
  Users(
    filter: {userName: {equalTo: "raghav"}, Account: {accountStatus: {equalTo: "active"}}}
  ) {
    nodes {
      userName
      Account {
        accountName
        accountId
        accountStatus
      }
    }
    totalCount
  }
}
```
**Error:**
 "message": "Field \"Account"\" is not defined by type \"UsersFilter\".

**Comment by Prabhanjali** [comment]
Hey! I found the issue, 
I just missed placing **connectionFilterRelations: true** inside **graphileBuildOptions**.
```
graphileBuildOptions: {
      connectionFilterRelations: true, // default: false
 }
 ```
 Adding this worked!
