### ISSUE TITLE
Postgraphile@v5 keeps failing in a docker container 

### ISSUE THREAD

**Issue by MarioSimou** [graphile/crystal#2026]
### Summary
Since yesterday, I have been encountering issues with Postgraphile in my Docker container. The container was working fine until yesterday afternoon, when it started throwing the error `SyntaxError: Named export 'makePgService' not found`. 

![image](https://github.com/graphile/crystal/assets/32243459/1b5386d7-e269-408d-b86a-0aed9bc34a54)

In an attempt to resolve this, I tried updating the `postgraphile/adaptors/pg` import:

```typescript
import pkg from 'postgraphile/adaptors/pg';
const { makePgService } = pkg;
```

But then, I started experiencing errors related to missing `graphile-build-pg` and `graphile-build`. Based on my understanding, those dependencies live in `postgraphile`. Despite this, I attempted to install them, but unfortunately, I was unsuccessful.

![image](https://github.com/graphile/crystal/assets/32243459/0f13ef14-5556-4364-bfbd-8c25b525f34a)

It's worth noting that the **issue only occurs within the container**. When I build the service locally, it runs without any problems. Since I'm using an Ubuntu 20.04 machine, I suspected that the `node:iron-alpine` image might be the cause of the problem, so I attempted to build the image using `node:20-bullseye-slim`. However, I encountered the same issue.

I'm also using these plugins:
- postgraphile-plugin-connection-filter@3.0.0-beta.2
- @graphile/simplify-inflection@8.0.0-beta.4
- @graphile/pg-aggregates@0.2.0-beta.5

Maybe something has changed on these, but I can't figure out what.

### Steps to reproduce
Build and run docker image.

### Expected results
Run service without any problems.

### Actual results
The service fails to start.

**Comment by benjie** [comment]
I don't generally offer support with Docker issues (for that, I recommend you reach out on the #help-docker channel on our Discord at https://discord.gg/graphile) so I'm going to close this.

However, I might still continue to provide more help in the closed issue if you're able to provide a minimal reproducible example. I suggest you create a repository with a `Dockerfile` in it and whatever else is necessary to reproduce the issue (keyword: **minimal** - absolutely nothing extraneous should be included) along with instructions that can be followed (e.g. how to run the Docker build, how to run the image, what parameters to pass at each stage, etc).

**Comment by MarioSimou** [comment]
The issue mentioned above was related to pnpm@v9 and how it constructs the dependency graph in a monorepo. After reverting back to v8, everything functioned as intended.
