### ISSUE TITLE
How to query a key that has ":" in the dictionary

### ISSUE THREAD

**Issue by Prabhanjali** [graphile/crystal#2027]
### Summary
Suppose I have my data as below
```
{
    "col1" : "firstcolumn",
    "col2" : "secondcolumn",
    "col3" : {
	 "abc:text" : "environment",
	 "cde"      : "hello"
    }
}
```

Now if I want to filter the rows that has **cde** as key and  value **hello**, I can use the below query
```
query{
    table(filter : {col3 : {contains : {cde : "hello"}}}){
	nodes{
	    col2,
	    col1
	}
    }
}
```

How to query if I want to get the rows where the key is having a **colon** (:) in it? 
Ex: How to query if I need to get the rows that has **abc:text** as key and value is **environment**?

**Comment by benjie** [comment]
A [GraphQL Name](https://spec.graphql.org/draft/#Name) cannot contain a `:` so this cannot occur.

**Comment by Prabhanjali** [comment]
But, I have a key named as **cde:tag1** and its value is **value1**. Can't I filter based on this?

**Comment by benjie** [comment]
A key in what? Do you mean a column in your database? Or a key in a JSON object? Or...?

**Comment by Prabhanjali** [comment]
A key in JSON Object

**Comment by benjie** [comment]
We don't have any built in functionality for querying JSON fields; use `makeAddPgTableConditionPlugin` or similar to make your own filter however you want (or use a database function).
