### ISSUE TITLE
Development mode warning printed when in test mode

### ISSUE THREAD

**Issue by nwjsmith** [graphile/crystal#2028]
### Steps to reproduce

Run `GRAPHILE_ENV=test node -e 'require("postgraphile")'` or `NODE_ENV=test node -e 'require("postgraphile")'`

### Expected results

Since we're explicitly in test mode, I would expect to see no warnings meant to catch production deployments of Grafast's development mode.

### Actual results

When running `GRAPHILE_ENV=test node -e 'require("postgraphile")'`:

```
Grafast is running in development mode due to `GRAPHILE_ENV=test`; this is recommended for development environments (and strongly discouraged in production), but will impact on performance - in particular, planning will be significantly more expensive.
```

When running `NODE_ENV=test node -e 'require("postgraphile")'`

```
Grafast is running in development mode due to `NODE_ENV=test`; this is recommended for development environments (and strongly discouraged in production), but will impact on performance - in particular, planning will be significantly more expensive.
```

### Additional context

Filed [as suggested in the Discord forum](https://discord.com/channels/489127045289476126/1230865104136962119/1230865653762625649).

**Comment by benjie** [comment]
Can confirm this was fixed in Feb (but currently unreleased): https://github.com/graphile/crystal/commit/4d9f83dc6af5af94ead017b2c06a63bb5e55b3b7

**Comment by nwjsmith** [comment]
Thank you!
