### ISSUE TITLE
Allow adding validation rules to Grafserv

### ISSUE THREAD

**Issue by nckswt** [graphile/crystal#2030]
### Feature description

Right now there's no easy way to include the `@graphile/depth-limit` plugin in a Grafserv setup.

### Motivating example

See [this thread](https://discord.com/channels/489127045289476126/498852330754801666/1232081526649393234) for full context.

### Supporting development

I [tick all that apply]:

- [ ] am interested in building this feature myself
- [ ] am interested in collaborating on building this feature
- [x] am willing to help testing this feature before it's released
- [ ] am willing to write a test-driven test suite for this feature (before it exists)
- [ ] am a [Graphile sponsor](https://www.graphile.org/sponsor/) ❤️
- [ ] have an active [support or consultancy contract](https://www.graphile.org/support/) with Graphile

**Comment by benjie** [comment]
Moved to the Crystal repo because it's Grafserv that needs to add support for adding validation rules rather than the other way around.

**Comment by benjie** [comment]
Fixed in #2046
