### ISSUE TITLE
Connection string with localhost don't work in library mode

### ISSUE THREAD

**Issue by sidux** [graphile/crystal#2053]
Hi,

When using a connection string with localhost for example `DATABASE_URL=postgres://dev:dev@localhost:5430/db` doesn't work in library mode but works fine in Command line mode, I had to use `127.0.0.1` instead.

**Comment by benjie** [comment]
The CLI takes the flags and converts them into library-mode equivalents, e.g. here's where it takes the `connection` CLI flag and adds it to the configuration for library mode:

https://github.com/graphile/crystal/blob/6124725cf5a3f91d5e838484b1919b236dfe4a9b/postgraphile/postgraphile/src/cli.ts#L204-L212

Please can you show a reproduction of your issue?

**Comment by sidux** [comment]
Actually it's due the `-c` option not really related to the library mode.

file : .env 

`DATABASE_URL=postgres://dev:dev@locahost:5430/flashdb`


file : graphile.config.js

```
mport { PostGraphileAmberPreset } from "postgraphile/presets/amber";
import { PgSimplifyInflectionPreset } from "@graphile/simplify-inflection";
import { makePgService } from "postgraphile/adaptors/pg";
import dotenv from "dotenv";

dotenv.config({ path: ".env" });

const preset = {
  extends: [PostGraphileAmberPreset, PgSimplifyInflectionPreset],
  schema: {
    pgJwtSecret: process.env.JWT_SECRET,
  },
  gather: {
    pgJwtTypes: "jwt_token",
  },
  pgServices: [
    makePgService({
      connectionString: process.env.DATABASE_URL,
      pubsub: true,
    }),
  ],
  grafserv: { watch: true },
};

export default preset;
```

when running `postgraphile` it doesn't work (error : `postgres says: Error: getaddrinfo ENOTFOUND locahost`)
when running `postgraphile -c 'postgres://dev:dev@localhost:5430/flashdb'` it works fine

If edit .env file with : 

`DATABASE_URL=postgres://dev:dev@127.0.0.1:5430/flashdb`

both work fine

**Comment by benjie** [comment]
You’ve misspelt `localhost` as `locahost`.

**Comment by sidux** [comment]
Oh yeah sorry, but still after fixing it `DATABASE_URL=postgres://dev:dev@localhost:5430/flashdb`

`postgraphile` command works
but 
`bun server.ts` doesn't work

both work well with `127.0.0.1`

here is my server.ts

```typescript
import Fastify from "fastify";
import { grafserv } from "grafserv/fastify/v4";
import preset from "./graphile.config.js";
import postgraphile from "postgraphile";

const pgl = postgraphile(preset);
const server = pgl.createServ(grafserv);
const app = Fastify({ logger: true });

server.addTo(app).catch((e) => {
  console.error(e);
  process.exit(1);
});

app.listen({ port: preset.grafserv?.port ?? 5678 }, (err, address) => {
  if (err) throw err;
  console.log(`Server is now listening on ${address}`);
});
```

**Comment by sidux** [comment]
Btw I understood the real cause, it's works well with `localhost` in tsx but doesn't with `bun` for some reason I have to use `127.0.0.1` instead for bun to work.

**Comment by benjie** [comment]
Please in future mention you’re using bun up front, this probably goes for filing an issue against any Node.js module that you’re having issues with under bun or any alternative runtime. Glad you figured it out.
