### ISSUE TITLE
How does Postgraphile integrate with Apache AGE?

### ISSUE THREAD

**Issue by FelixZY** [graphile/crystal#2068]
### Summary

I'm looking to design an open data source to be exposed via GraphQL. In my research, I've found the concept of graph databases quite interesting. I'm also inclined to think that there may be benefits to gain from having the GraphQL API sitting on top of a graph database.

Based on this, I've ended up looking at [Apache AGE](https://age.apache.org/). I'm also planning on going with Postgraphile (even if I can't use AGE in the end). However, I can't seem to find any articles, tutorials or documentation on whether Postgraphile integrates well with AGE. Hence, I have some questions:
1. Is AGE officially supported by Postgraphile?
2. Does Postgraphile integrate well with AGE?
3. Do you agree with my theory that using a graph based backend would have benefits when exposing a GraphQL API?

**Comment by benjie** [comment]
> Is AGE officially supported by Postgraphile?

No.

> Does Postgraphile integrate well with AGE?

No idea. Does it? Let us know how you get on.

> Do you agree with my theory that using a graph based backend would have benefits when exposing a GraphQL API?

GraphQL doesn’t really have anything to do with graph databases and works fine with almost any datasource that contains objects and relationships between them. All technologies have tradeoffs, so it might have some benefits and some disadvantages. I’m only superficially familiar with graph databases so can’t weigh in too much on it.

I’m going to close this but feel free to keep discussing below.
