### ISSUE TITLE
How to call custom function with the id provided by the relay preset

### ISSUE THREAD

**Issue by FelixZY** [graphile/crystal#2086]
### Summary

I'm trying to set up a function like this:

```sql
CREATE
OR REPLACE function dansdata.add_organization_member (
  organization_id UUID,
  individual_id UUID,
  title TEXT
) returns dansdata.organization_members AS $$
  INSERT INTO dansdata.organization_members("organization_id", "individual_id", "title") VALUES (organization_id, individual_id, title) RETURNING *;
$$ language sql volatile strict security invoker;
```

However, attempting to call the function like this (using the relay preset) does not seem to work:

```gql
mutation {
  addOrganizationMember(input: {
    organizationId: "WyJPcmdhbml6YXRpb24iLCI3YjA4OGVkOC0wYzkzLTRlZTUtODdlYi05YWU4NTMxZDgwMGYiXQ",
    individualId: "WyJJbmRpdmlkdWFsIiwiNjU3YmI0ODMtOGUzNy00ODA2LTlkYzAtMWZjZGM0OWEzMTkxIl0",
    title: "Developer"
  }) {
    result {
      id
      title
      individual {
        name
      }
      organization {
        name
      }
    }
  }
}
```

<details><summary>Error</summary>

```json
{
  "errors": [
    {
      "message": "Invalid UUID, expected 32 hexadecimal characters, optionally with hypens",
      "extensions": {}
    },
    {
      "message": "Invalid UUID, expected 32 hexadecimal characters, optionally with hypens",
      "extensions": {}
    }
  ]
}
```

</details>

Instead, it seems I need to use the actual `rowId` instead:

```gql
mutation {
  addOrganizationMember(input: {
    organizationId: "7b088ed8-0c93-4ee5-87eb-9ae8531d800f",
    individualId: "657bb483-8e37-4806-9dc0-1fcdc49a3191",
    title: "Developer"
  }) {
    result {
      id
      title
      individual {
        name
      }
      organization {
        name
      }
    }
  }
}
```

which is very inconvenient given that `rowId` isn't available when using the relay preset.

The [documentation](https://postgraphile.org/postgraphile/next/node-id#more-on-the-relay-preset:~:text=(and%2C%20with%20a%20little%20guidance%2C%20in%20function%20inputs).) mentions that the relay preset "[...] will hide raw primary keys from most of the schema, and will use global object identifiers instead - not just in the query schema but also in mutations and filtering (and, **with a little guidance, in function inputs**).".

Given this, I'm assuming my first example is supposed to work but that I need to add some sort of configuration somewhere. Unforutnately, the current documentation does not currently elaborate on what "a little guidance" entails.

### Additional context

PostgreSQL: docker - `postgis/postgis:16-3.4-alpine`
Node: v20.14.0
Postgraphile: 5.0.0-beta.26

**Comment by benjie** [comment]
We need to add it to https://postgraphile.org/postgraphile/next/node-id/
and cross-link it to https://postgraphile.org/postgraphile/next/smart-tags/#arg0variant-arg1variant-
and I could have sworn that I'd written it in the docs somewhere but I can't find it (please PR!) but essentially you need to:

1. create the function so that it accepts a table record type rather than uuid (this is a temporary requirement we hope to lift at some point, but we'll need another way of indicating the expected type)
2. override autodetection if it's a stable function (as we might detect it as a computed column function) to turn it back into what it should be: `@behavior -queryField -typeField -mutationField +queryField`. No action necessary for yours since it's `volatile`
3. change the "variant" of the relevant 0-indexed argument to `nodeId`: `@arg0variant nodeId\n@arg1variant nodeId`


So for you:

```sql
CREATE
OR REPLACE function dansdata.add_organization_member (
  organization dansdata.organizations,
  individual dansdata.individuals,
  title TEXT
) returns dansdata.organization_members AS $$
  INSERT INTO dansdata.organization_members("organization_id", "individual_id", "title") VALUES (organization.id, individual.id, title) RETURNING *;
$$ language sql volatile strict security invoker;
comment on function dansdata.add_organization_member is
  E'@arg0variant nodeId\n@arg1variant nodeId\n@behavior -typeField +mutationField';
```

**Comment by FelixZY** [comment]
@benjie, thanks to your description, I was able to implement the desired behavior. However, given the current requirement of using a table record type, I found myself having to deal with two instances of "ugly" DX. For me, these are further motivating the need to support `@arg0variant nodeId` on non-table record types, such as `uuid`, in the future as well.

### 1. `id` duplication

```sql
CREATE OR REPLACE function dansdata.add_organization_member (
  organization_id dansdata.organizations,
  member_id dansdata.profiles,
  title TEXT = NULL
) returns dansdata.organization_members AS $$
  SELECT dansdata.add_organization_member (organization_id.id, member_id.id, title);
$$ language sql volatile called ON NULL input security invoker;
```

As you can see, I now have to use `<type>_id.id` syntax to access my id if I want to expose `organizationId: <id>` in the GraphQL api.

Of course, I could just

```sql
CREATE OR REPLACE function dansdata.add_organization_member (
  organization dansdata.organizations,
  member dansdata.profiles,
  title TEXT = NULL
)
```

but then the GraphQL member will be named `organization` instead of `organizationId` (I'm guessing I could work around this with inflection but that's still a bit too much work IMO).

### 2. It's harder to use the function internally

I can no longer simply do this in raw SQL:

```sql
SELECT dansdata.add_organization_member ('68d3ca81-52ba-484d-80b6-ca0af6213c1d', 'f0f98228-e7fe-418c-b71e-995638862ee7');
```

instead, I've been forced to add a wrapper specifically for postgraphile which I would preferably avoid:

```sql
CREATE OR REPLACE function dansdata.add_organization_member (
  organization_id UUID,
  member_id UUID,
  title TEXT = NULL
) returns dansdata.organization_members AS $$
  INSERT INTO
    dansdata.organization_members ("organization_id", "member_id", "title")
  VALUES
    (organization_id, member_id, title)
  RETURNING
    *;
$$ language sql volatile called ON NULL input security invoker;

comment ON function dansdata.add_organization_member IS $$
  @behavior -*
$$;

CREATE OR REPLACE function dansdata.postgraphile_add_organization_member (
  organization_id dansdata.organizations,
  member_id dansdata.profiles,
  title TEXT = NULL
) returns dansdata.organization_members AS $$
  SELECT dansdata.add_organization_member (organization_id.id, member_id.id, title);
$$ language sql volatile called ON NULL input security invoker;

comment ON function dansdata.postgraphile_add_organization_member IS $$
  @name addOrganizationMember
  @arg0variant nodeId
  @arg1variant nodeId
$$;
```

**Comment by benjie** [comment]
I'm well aware of the limitations, and this is a planned feature. The reason we don't support it on `UUID` currently is because we have no way of indicating what _type_ that UUID is meant to be, other than to use a record type. Likely a better solution is to use something like `@arg0variant nodeId:Organization` but implementing that is not something that has been visited yet. But since it is solvable in the current system (albeit slightly awkward) it's on the backburner to address once V5.0.0 is released.
