### ISSUE TITLE
How to Modify the Result of a PgSelectStep

### ISSUE THREAD

**Issue by iamameme** [graphile/crystal#2161]
I know that `PgSelectStep` is opaque and cannot be fed into another step. I'm thinking this isn't possible but, is there a way to modify the result of this step?

Example:
The GraphQL schema we have has some legacy fields. One field, for example, returns the same values as the database, but the key names are slightly different. Such as `is_primary` and is instead `isPrimary`. 

Right now, we are using a `withPgClient` step to make the same query we would make with a `PgSelectStep` in order to have the values of the rows so we can modify the names of the keys.

Is there a better way to do this? Thank you :)

In code:

What I want to do:
```
const $allocations = team_allocation.find();
const frag = $allocations.placeholder($workdayId, TYPES.text);
$allocations.where(sql`${$allocations.alias}."teamId" = ${frag}`);

return loadMany(
              list([$allocations, $warLegacyId]),
              ['allocations', 'warLegacyId'],
              ([allocations, warLegacyId]: any) => {
                return allocations.map((allocation: any) => ({
                  _created: allocation.createdAt.toISOString(),
                  _updated: allocation.updatedAt.toISOString(),
                  _version: 123456789, // DEPRECATED
                  allocation_group_id: warLegacyId,
                  is_primary: allocation.isPrimary,
                  lastSync: allocation.updatedAt.toISOString(),
                  person_rid: allocation.personRid,
                }));
              },
            );
```
Then take the result of this and modify it slightly

What we are doing instead:
```
const $teamAllocations = withPgClient(
              teamExecutor,
              list([$workdayId, $warLegacyId]),
              async (pgClient, [workdayId, warLegacyId]) => {
                if (!workdayId || !warLegacyId) return null;

                const teamAllocations = await pgClient.query<{ id: number }>({
                  text: `select * from team_allocation where "teamId" = $1`,
                  values: [workdayId],
                });

                return teamAllocations.rows.map((allocation: any) => ({
                  _created: allocation.createdAt.toISOString(),
                  _updated: allocation.updatedAt.toISOString(),
                  _version: 123456789, // DEPRECATED
                  allocation_group_id: warLegacyId,
                  is_primary: allocation.isPrimary,
                  lastSync: allocation.updatedAt.toISOString(),
                  person_rid: allocation.personRid,
                }));
              },
            );
```

**Comment by benjie** [comment]
Instead of `list([$allocations, $warLegacyId])` in your first example, you could use `list([$resolvedAllocations, $warLegacyId])` where:

```ts
const $resolvedAllocations = applyTransforms(each($allocations, $a => object({
  createdAt: $a.get('createdAt'),
  updatedAt: $a.get('updatedAt'),
  isPrimary: $a.get('isPrimary'),
  personRid: $a.get('personRid'),
})));
```

Not sure if this is what you're looking for?

**Comment by iamameme** [comment]
This is exactly what I was looking for! Thank you so much. I couldn't find this anywhere in the documentation or code! Think it would be worth opening a PR and adding some documentation around this? I think people would find it very useful.

**Comment by benjie** [comment]
Yes please; see this issue and the linked discussion for some hints on documenting it:

https://github.com/graphile/crystal-pre-merge/issues/416

Also if you get into the documentation mood... there's 27 other issues that could do with some attention - have a look in the "Docs Improvements" column:

https://github.com/orgs/graphile/projects/3/views/1

**Comment by benjie** [comment]
Closing this as I think it's covered by https://github.com/graphile/crystal-pre-merge/issues/416

**Comment by iamameme** [comment]
I am in a documentation mood! I took my first stab at writing documentation around this, and if all goes well, will move onto more on that list :) 

https://github.com/graphile/crystal/pull/2163
