### ISSUE TITLE
How to Remove an Endpoint Created From a Uniqueness Constraint

### ISSUE THREAD

**Issue by machineghost** [graphile/crystal#2264]
### Summary

I'm using Postgraphile 4, and have a `users` table with an `email` column and a `UNIQUE` constraint (`users_email_unique`) on that column.  This generates a `userByEmail` endpoint in GraphQL...  which I would like to remove from my API.

I've tried:

    COMMENT ON CONSTRAINT users_email_unique ON public.users IS E'@omit all'; 

and:

    COMMENT ON CONSTRAINT users_email_unique ON public.users IS E'@skip'; 

... but neither of them removes the GraphQL field.

### Additional context

It would  be super helpful if the documentation contained more examples.  Even a single (one-line) example of omiting (skipping? hiding?) *any* constraints (unique or foreign) would have been great.

**Comment by benjie** [comment]
[`@omit all`](https://postgraphile.org/postgraphile/current/smart-tags#omit) causes the "allBlahs" query field to be omitted - looks like you're attempting to omit the single accessor field which is not something that V4 supports. In V4 you can either:

- `@omit` entirely (i.e. don't list the things you want to omit, just use `@omit` on its own) which will completely ignore the constraint, or
- [remove the field after it is created](https://postgraphile.org/postgraphile/current/extending-raw#removing-things-from-the-schema)

In V5 you would use `@behavior -single` and the single field accessor would go away.

> It would be super helpful if the documentation contained more examples. Even a single (one-line) example of omiting (skipping? hiding?) any constraints (unique or foreign) would have been great.

Please do submit improvements to the documentation - this is an open source project!

Here's an example of somewhere in our documentation where it shows adding a comment to a constraint:

https://postgraphile.org/postgraphile/current/smart-comments#constraints

Maybe add another that just contains `@omit`?

**Comment by machineghost** [comment]
`@omit` did the trick, thanks!
