### ISSUE TITLE
Mutations on computed columns

### ISSUE THREAD

**Issue by ruipaulo** [graphile/crystal#559]
Hey postgraphql team, thanks for the amazing product you have built!

From my perspective one of the very powerful features of postgraphql is to create computed columns. Unfortunately, I found no way to do mutations on a computed column. It would be nice to be able to write functions that can process mutations on these columns.

**Comment by benjie** [comment]
@ruipaulo Could you lay out rough SQL and GraphQL schemas for what you want here? It's not immediately obvious what you mean "process mutations on these columns" given that they're computed. Do you mean combining a computed column "getter" (which we currently support) with a "setter" (which we don't), maybe?

**Comment by ruipaulo** [comment]
@benjie Exactly. It is supported to add a "virtual" getter function to a  table. Having setters would be super nice. 

A brief explanation of the use case: I have a data table (let's call it `movie`) and I enrich it based on the logged in user (for example the user's rating of the movie). I do this by writing a `movie_rating` function, which pulls the data from different other (private) tables. 

The rating can now be shown in the frontend easily, but it is difficult to update it. Therefore it would be nice to have that 'field' on the mutations, too. If a mutation having that field would be called, postgraphql would call a function, let's say `movie_rating_update`. This function would make the appropriate updates to the database.

**Comment by benjie** [comment]
Okay, so a computed column is evaluated like:

Definition:

```sql
create table foo (
  id serial primary key,
  a text,
  b text,
  c text,
  d text
);

create function foo_computed(f foo) returns text as $$ select f.a || f.b; $$ language sql stable;
```

Execution:

```sql
select a, b, foo_computed(foo) from foo;
```

---

How would a mutation work? I can't see a way to do it in the same statement as the `update` clause, which is problematic. e.g.

```sql
update foo set a = $1, b = $2, foo_computed_set($3) where id = $4;
```

isn't valid. We could maybe do something like:

```sql
create function foo_set_computed(f foo, value text) returns foo as $$
begin
  f.c = value || ' COMPUTED';
  return f;
end;
$$ language plpgsql volatile;
```

then do:

```sql
update foo set (id, a, b, c, d) = foo_set_computed((id, $1, $2, c, d)::foo, $3) where id = $4
```

The issue being that we may not have update permissions to all those columns. I can't think of a better way of doing it - anyone got any ideas?

**Comment by benjie** [comment]
I'm currently thinking we should follow up with a second statement to execute computed functions, e.g.

```
update table set ...;
select table_set_computed1(...);
select table_set_computed2(...);
```

Convention would be that they have to return the full table entry (like a trigger returns the NEW object) and then we can chain them.

**Comment by benjie** [comment]
Could maybe do a CTE chain if we do that:

```
with foo as (
  update table set ... where ... returning *
), bar as (
  select * from (select table_set_computed1(foo) from foo)
), baz as (
  select * from (select table_set_computed2(bar) from bar)
) select * from baz;
```

**Comment by mattether** [comment]
This has cropped up in a couple of places where it'd be useful for a project I'm working on.

I thought I might be able to workaround this by adding a dummy column with the comment `@omit read`, and use a before update/insert trigger to do what I wanted, but as I see now `@omit read` removes that field completely. It'd be nice if it was still available in the patch types, for create and update.

What's the reasoning behind `read` removing it completely?

**Comment by benjie** [comment]
> What's the reasoning behind read removing it completely?

Just a lack of time; thats why I require that you specify the other permissions along with `@omit read` so that in future I can remove that constraint without it being a breaking change.

(I think it was something to do with selecting the column from SQL after inserting/updating it?)

<details>
<summary>Here's a cumbersome way to achieve your goal</summary>

You can use `graphile-utils` to add an additional field to your input type

```
const {
  makeExtendSchemaPlugin,
  gql,
} = require('graphile-utils');

const MySchemaExtensionPlugin =
  makeExtendSchemaPlugin(
    build => ({
      typeDefs: gql`
        extend input MyTableInput {
          myComputedColumn: String
        }
      `,
      resolvers: {}
    })
  );
```

and then add another plugin that wraps the resolver (this is mostly boilerplate):

```
module.exports = function (builder) {
  builder.hook(
    "GraphQLObjectType:fields:field",
    (
      field,
      { pgSql: sql },
      { scope: { isRootMutation, fieldName }, addArgDataGenerator }
    ) => {
      if (!isRootMutation || fieldName !== "createMyTable") {
        return field;
      }
      // I really need to write an easier API for this part...
      addArgDataGenerator(() => ({
        pgQuery: queryBuilder => {
          queryBuilder.select(
            // Select this value from the result of the INSERT:
            sql.query`${queryBuilder.getTableAlias()}.id`,
            // And give it this name in the result data:
            "__createdRecordId"
          );
        },
      }));

      const defaultResolver = obj => obj[fieldName];

      const { resolve: oldResolve = defaultResolver, ...rest } = field;

      return {
        ...rest,

        async resolve(...resolveParams) {
          const [_mutation, args, context, resolveInfo] = resolveParams
          const { pgClient } = context;
          const oldResolveResult = await oldResolve(...resolveParams);
          const createdId = oldResolveResult.data.__createdRecordId;

          // Here's your part
          await pgClient.query('update my_table set something = $1 where id = $2', [args.myComputedColumn, createdId]);


          return oldResolveResult;
        },
      };
    }
  );
};
```

</details>


What SQL API would you like for setting your computed field?

**Comment by FuJa0815** [comment]
Hello, just wanted to chime in and ask about the status of this, is there an easy way of doing this?
My use-case is the following: I wanted to implement soft-delete for a table. I added the `deleted_at timestamptz NULL DEFAULT NULL` column to the table, but I don't want to simply expose this column for updating because I don't want to allow the client to set any timestamp. Instead I created a computed column:
```sql
CREATE FUNCTION public.foo_is_deleted(foo public.foo) RETURNS BOOLEAN AS $$
  SELECT foo.deleted_at IS NOT NULL
$$ LANGUAGE SQL STABLE;
```
And I would like to create a "setter" function like this:
```sql
CREATE FUNCTION public.foo_set_is_deleted(foo public.foo, is_deleted BOOLEAN) RETURNS public.foo AS $$
BEGIN
  foo.deleted_at = CASE WHEN is_deleted THEN NOW() ELSE NULL END;
  RETURN foo;
$$ LANGUAGE PLPGSQL VOLATILE;
```

Is there an easy way to do this?

**Comment by benjie** [comment]
In PostGraphile V5 `@behavior -select` on the column should accomplish this.
