### ISSUE TITLE
Custom aggregation in the connection procedures? (e.g. totalCount)

### ISSUE THREAD

**Issue by pencilcheck** [graphile/crystal#685]
I'm submitting a ... 
- [ ] bug report
- [x] feature request
- [ ] question 

Right now any custom procedure that returns a "setof" gets the relay style connection with totalCount as the only aggregation number.

I wonder if it is possible to add custom aggregation number next to totalCount for that custom procedure?

PostGraphQL version:

Minimal SQL file that can be loaded into a clean database:
``` sql

```

Steps to reproduce:

Current behavior:

Expected behavior:

**Comment by benjie** [comment]
This isn’t the first time this has been needed.

I wonder if we can do it using a behaviour similar to computed columns, or whether it’s more suitable as a plugin.

What aggragate are you looking for exactly?

**Comment by benjie** [comment]
Ugh spelling mistakes. Can’t fix, am on mobile, so I’ll just wallow in the shame 😜

**Comment by pencilcheck** [comment]
No problem, for instance, aggregate on revenue, which is multiplication of rate and time, etc

**Comment by benjie** [comment]
Ah interesting, so multi-column. I think using “create aggregate” to create a conputed-column-like interface is probably too arduous for most users - it’s generally more convenient to write in terms of the existing aggregate functions. As such i think it’d have to be a plugin. I’m not sure off the top of my head how complex that would be.

**Comment by pencilcheck** [comment]
Ah, the create aggregate looks interesting but I agree with your assessment. I wonder how hard is it to expose a "computed column" like interface where a function name can be parsed to put into a aggregate attribute in nodes or edges alike?

For example:
```
CREATE AGGREGATE clerk_aggregate_revenue(
  result_from_expression_related_to_setof_clerk clerk
) RETURNS text AS $$

  select agg(rate * hours) from result_from_expression_related_to_setof_clerk

$$ language sql stable;

```

And this function is automatically run on every "setof clerk" expression and shows a "revenue" attribute next to "totalCount".

Is this possible?

**Comment by benjie** [comment]
Passing an entire `setof` collection to a function is a very expensive thing to do if that's what you're suggesting.

**Comment by pencilcheck** [comment]
How would you suggest doing this as a first step? Right now if I were to do this I would need to create a separate function doing the same thing and only output the aggregate value at the end instead of the `setof` collection.

**Comment by benjie** [comment]
Well, totalCount uses this plugin:

https://github.com/graphile/graphile-build/blob/eb1a6bc6910a54907ce6098acee19503b0004d38/packages/graphile-build-pg/src/plugins/PgConnectionTotalCount.js

But it's a bit of a hack because it just flags `pgCalculateTotalCount`, which effectively adds this to the SQL query:

https://github.com/graphile/graphile-build/blob/45e916f2ea85e5263c968ea1c1c975d5dbcada40/packages/graphile-build-pg/src/queryFromResolveData.js#L232-L236

We could make that code more plugin-able though. Just takes time.

**Comment by pencilcheck** [comment]
I see. That's cool.

Something on the side: Perhaps there is a way to automatically create an index or a temporary table that postgraphql use to keep track of the default totalCount?

**Comment by benjie** [comment]
We use a CTE which is not dissimilar to a temporary table. I did try making an actual temporary table, but the permissions required would be a barrier to many use cases so it wasn't feasible to use by default.

**Comment by benjie** [comment]
We have plugin support for custom aggregation on connections now, it was introduced as part of 4.4. We don't have any in core yet, but here's an example plugin:

https://github.com/graphile/pg-aggregates

(Copy the code into your own repo, it's just an experiment right now.)

`totalCount` has been re-written to use the new aggregates infrastructure, so it can act as a good starting point:

https://github.com/graphile/graphile-engine/blob/e68291bdd065b5711f066f1f11c0ac3539518cf0/packages/graphile-build-pg/src/plugins/PgConnectionTotalCount.js#L38-L43

**Comment by benjie** [comment]
This has long been possible via the pg-aggregates plugin.
