### ISSUE TITLE
Build new .postgraphilerc system using library options.

### ISSUE THREAD

**Issue by benjie** [graphile/crystal#705]
It would be nice to add, e.g.

```js
module.exports = {
  options: {
    graphileBuildOptions: {
      pgStrictFunctions: true,
    },
  },
};
```

to `.postgraphilerc.js` in order to enable pgStrictFunctions (or other similar things) in the CLI version.

**Comment by benjie** [comment]
We should also document graphileBuildOptions in the library.

**Comment by benjie** [comment]
I want to deprecate the existing postgraphilerc file and add a better one that uses the library options (which are better documented and more flexible).

**Comment by bostrom** [comment]
> We should also document graphileBuildOptions in the library.

I was just about to open an issue about `pgStrictFunctions` not being listed in the "Library usage" section of the docs. I guess the `graphileBuildOptions` documentation would cover that too, since they don't seem to be documented anywhere?

**Comment by benjie** [comment]
Yep. There’s a lot of little hidden options like that; help tracking them down and making a page (maybe under “Usage”?) for them would be great. I’ll of course fix the copy if it’s not accurate. Another place to search for their meanings is the releases on PostGraphile repo; often they’re ways of disabling fixes that could potentially break super-edge-case usage. Honestly I’m not sure if anyone’s ever used any of those 🤷‍♂️

**Comment by jhg03a** [comment]
When it comes to Docker utilization, it would be nice to be able to mount in a file containing all the options, if they're not going to have environment variable equivalents universally.

**Comment by benjie** [comment]
https://dev.to/graphile/intro-to-postgraphile-v5-part-2-plugins-and-presets-26fe

**Comment by benjie** [comment]
Resolved via `graphile-config` presets - see above blog post.
